name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh issue list -s all
      - uses: education/autograding@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATUS_READER }}
          GH_TOKEN: ${{ secrets.GH_STATUS_READER }}


